md build
md dist
md dist\assets
md dist\assets\css
md dist\assets\fonts
md dist\assets\images
md dist\assets\images\favicon
md dist\assets\js
md node_modules
md src
md src\scss
md src\scss\components
md src\scss\elements
md src\scss\generic
md src\scss\objects
md src\scss\settings
md src\scss\tools
md src\scss\utilities
md src\scss\vendor
md src\scss\vendor\bootstrap
md src\scss\vendor\bootstrap\js
md src\scss\vendor\bootstrap\js\src
md src\scss\vendor\bootstrap\scss
md src\scss\vendor\bootstrap.icons
md src\scss\vendor\fontawesome
